routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthGitHub;
use App\Http\Controllers\DirMarkController;
use App\Http\Controllers\DealController;
use App\Http\Controllers\DirRoleController;
use App\Http\Controllers\DirSourceController;
use App\Http\Controllers\DirStageController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale) {
    if (! in_array($locale, ['en', 'ru', 'de'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/', function () {
    return view('welcome');
});

Route::get('login/github', [AuthGitHub::class, 'redirectToProvider']);
Route::get('login/github/callback', [AuthGitHub::class, 'handleProviderCallback']);

Auth::routes();
Route::group( ['middleware' => 'auth' ], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('dirmark', DirMarkController::class);
    Route::resource('dirrole', DirRoleController::class);
    Route::resource('dirsource', DirSourceController::class);
    Route::resource('dirstage', DirStageController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('deal', DealController::class);
    Route::resource('user', UserController::class);
});

app/DirSource.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class DirSource
 *
 * @property $id
 * @property $name
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class DirSource extends Model
{
    protected $primaryKey = 'id';
    public $timestamps = false;

    static $rules = [
		'name' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name'];



}

app/Http/Controllers/DirSourceController.php
<?php

namespace App\Http\Controllers;

use App\DirSource;
use Illuminate\Http\Request;

/**
 * Class DirSourceController
 * @package App\Http\Controllers
 */
class DirSourceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dirSources = DirSource::paginate();

        return view('dir-source.index', compact('dirSources'))
            ->with('i', (request()->input('page', 1) - 1) * $dirSources->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dirSource = new DirSource();
        return view('dir-source.create', compact('dirSource'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(DirSource::$rules);

        $dirSource = DirSource::create($request->all());

        return redirect()->route('dirsource.index')
            ->with('success', 'DirSource created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dirSource = DirSource::find($id);

        return view('dir-source.show', compact('dirSource'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dirSource = DirSource::find($id);

        return view('dir-source.edit', compact('dirSource'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  DirSource $dirSource
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate(DirSource::$rules);
        DirSource::find($id)->update($request->all());

        return redirect()->route('dirsource.index')
            ->with('success', 'DirSource updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $dirSource = DirSource::find($id)->delete();

        return redirect()->route('dirsource.index')
            ->with('success', 'DirSource deleted successfully');
    }
}

resources/views/dir-source/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.Create') }} {{ __('all.DirSource') }}
@endsection

@section('template_button')
    <a href="{{ route('dirsource.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-body">
                        <form method="POST" action="{{ route('dirsource.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('dir-source.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dir-source/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.Update') }} {{ __('all.DirSource') }}
@endsection

@section('template_button')
    <a href="{{ route('dirsource.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-body">
                        <form method="POST" action="{{ route('dirsource.update', $dirSource->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('dir-source.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dir-source/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            {{ Form::label(__('all.table.Name')) }}
            {{ Form::text('name', $dirSource->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => __('all.table.Name')]) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('all.button.Submit') }}</button>
    </div>
</div>

resources/views/dir-source/index.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.DirSource') }}
@endsection

@section('template_button')
    <a href="{{ route('dirsource.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
        <i class="fas fa-plus-circle"></i> {{ __('all.button.CreateNew') }}
    </a>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    @include('layouts.alerts.success')

                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead class="thead">
                                <tr>
                                    <th>{{ __('all.table.No') }}</th>

                                    <th>{{ __('all.table.Name') }}</th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($dirSources as $dirSource)
                                    <tr>
                                        <td>{{ ++$i }}</td>

                                        <td>{{ $dirSource->name }}</td>

                                        <td>
                                            <form action="{{ route('dirsource.destroy',$dirSource->id) }}" method="POST">
                                                <a class="btn btn-sm btn-primary " href="{{ route('dirsource.show',$dirSource->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('all.button.Show') }}</a>
                                                <a class="btn btn-sm btn-success" href="{{ route('dirsource.edit',$dirSource->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('all.button.Edit') }}</a>
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> {{ __('all.button.Delete') }}</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>

                    {!! $dirSources->links() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dir-source/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.button.Show') }} {{ __('all.DirSource') }}
@endsection

@section('template_button')
    <a href="{{ route('dirsource.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-body">

                        <div class="form-group">
                            <strong>{{ __('all.table.Name') }}:</strong>
                            {{ $dirSource->name }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection