routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthGitHub;
use App\Http\Controllers\DirMarkController;
use App\Http\Controllers\DealController;
use App\Http\Controllers\DirRoleController;
use App\Http\Controllers\DirSourceController;
use App\Http\Controllers\DirStageController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale) {
    if (! in_array($locale, ['en', 'ru', 'de'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/', function () {
    return view('welcome');
});

Route::get('login/github', [AuthGitHub::class, 'redirectToProvider']);
Route::get('login/github/callback', [AuthGitHub::class, 'handleProviderCallback']);

Auth::routes();
Route::group( ['middleware' => 'auth' ], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('dirmark', DirMarkController::class);
    Route::resource('dirrole', DirRoleController::class);
    Route::resource('dirsource', DirSourceController::class);
    Route::resource('dirstage', DirStageController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('deal', DealController::class);
    Route::resource('user', UserController::class);
});

app/DirStage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class DirStage
 *
 * @property $id
 * @property $name
 * @property $num_pp
 * @property $color
 *
 * @property Deal[] $deals
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class DirStage extends Model
{
    protected $primaryKey = 'id';
    public $timestamps = false;

    static $rules = [
		'name' => 'required',
		'num_pp' => 'required',
		'color' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name','num_pp','color'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function deals()
    {
        return $this->hasMany('App\Deal', 'id_stage', 'id');
    }


}

app/Http/Controllers/DirStageController.php
<?php

namespace App\Http\Controllers;

use App\DirStage;
use Illuminate\Http\Request;

/**
 * Class DirStageController
 * @package App\Http\Controllers
 */
class DirStageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dirStages = DirStage::paginate();

        return view('dir-stage.index', compact('dirStages'))
            ->with('i', (request()->input('page', 1) - 1) * $dirStages->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dirStage = new DirStage();
        return view('dir-stage.create', compact('dirStage'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(DirStage::$rules);

        $dirStage = DirStage::create($request->all());

        return redirect()->route('dirstage.index')
            ->with('success', 'DirStage created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dirStage = DirStage::find($id);

        return view('dir-stage.show', compact('dirStage'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dirStage = DirStage::find($id);

        return view('dir-stage.edit', compact('dirStage'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  DirStage $dirStage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate(DirStage::$rules);
        DirStage::find($id)->update($request->all());

        return redirect()->route('dirstage.index')
            ->with('success', 'DirStage updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        DirStage::find($id)->delete();

        return redirect()->route('dirstage.index')
            ->with('success', 'DirStage deleted successfully');
    }
}

resources/views/dir-stage/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.Create') }} {{ __('all.DirStage') }}
@endsection

@section('template_button')
    <a href="{{ route('dirstage.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-body">
                        <form method="POST" action="{{ route('dirstage.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('dir-stage.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dir-stage/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.Update') }} {{ __('all.DirStage') }}
@endsection

@section('template_button')
    <a href="{{ route('dirstage.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-body">
                        <form method="POST" action="{{ route('dirstage.update', $dirStage->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('dir-stage.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dir-stage/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            {{ Form::label(__('all.table.Name')) }}
            {{ Form::text('name', $dirStage->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => __('all.table.Name')]) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label(__('all.table.num_pp')) }}
            {{ Form::text('num_pp', $dirStage->num_pp, ['class' => 'form-control' . ($errors->has('num_pp') ? ' is-invalid' : ''), 'placeholder' => __('all.table.num_pp')]) }}
            {!! $errors->first('num_pp', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label(__('all.table.Color')) }}
            {{ Form::color('color', $dirStage->color, ['class' => 'form-control' . ($errors->has('color') ? ' is-invalid' : ''), 'placeholder' => __('all.table.Color')]) }}
            {!! $errors->first('color', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('all.button.Submit') }}</button>
    </div>
</div>

resources/views/dir-stage/index.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.DirStage') }}
@endsection

@section('template_button')
    <a href="{{ route('dirstage.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
        <i class="fas fa-plus-circle"></i> {{ __('all.button.CreateNew') }}
    </a>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    @include('layouts.alerts.success')

                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead class="thead">
                                <tr>
                                    <th>{{ __('all.table.No') }}</th>

                                    <th>{{ __('all.table.Name') }}</th>
                                    <th>Num Pp</th>
                                    <th>{{ __('all.table.Color') }}</th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($dirStages as $dirStage)
                                    <tr>
                                        <td>{{ ++$i }}</td>

                                        <td>{{ $dirStage->name }}</td>
                                        <td>{{ $dirStage->num_pp }}</td>
                                        <td>{{ $dirStage->color }}</td>

                                        <td>
                                            <form action="{{ route('dirstage.destroy',$dirStage->id) }}" method="POST">
                                                <a class="btn btn-sm btn-primary " href="{{ route('dirstage.show',$dirStage->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('all.button.Show') }}</a>
                                                <a class="btn btn-sm btn-success" href="{{ route('dirstage.edit',$dirStage->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('all.button.Edit') }}</a>
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> {{ __('all.button.Delete') }}</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {!! $dirStages->links() !!}
        </div>
    </div>
</div>
@endsection

resources/views/dir-stage/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.button.Show') }} {{ __('all.DirStage') }}
@endsection

@section('template_button')
    <a href="{{ route('dirstage.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        <div class="form-group">
                            <strong>{{ __('all.table.Name') }}:</strong>
                            {{ $dirStage->name }}
                        </div>
                        <div class="form-group">
                            <strong>{{ __('all.table.num_pp') }}:</strong>
                            {{ $dirStage->num_pp }}
                        </div>
                        <div class="form-group">
                            <strong>{{ __('all.table.Color') }}:</strong>
                            {{ $dirStage->color }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection