routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthGitHub;
use App\Http\Controllers\DirMarkController;
use App\Http\Controllers\DealController;
use App\Http\Controllers\DirRoleController;
use App\Http\Controllers\DirSourceController;
use App\Http\Controllers\DirStageController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', function ($locale) {
    if (! in_array($locale, ['en', 'ru', 'de'])) {
        abort(400);
    }
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/', function () {
    return view('welcome');
});

Route::get('login/github', [AuthGitHub::class, 'redirectToProvider']);
Route::get('login/github/callback', [AuthGitHub::class, 'handleProviderCallback']);

Auth::routes();
Route::group( ['middleware' => 'auth' ], function() {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('dirmark', DirMarkController::class);
    Route::resource('dirrole', DirRoleController::class);
    Route::resource('dirsource', DirSourceController::class);
    Route::resource('dirstage', DirStageController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('deal', DealController::class);
    Route::resource('user', UserController::class);
});

app/DirMark.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class DirMark
 *
 * @property $id
 * @property $name
 * @property $color
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class DirMark extends Model
{
    protected $primaryKey = 'id';
    public $timestamps = false;

    static $rules = [
		'name' => 'required',
		'color' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name','color'];



}

app/Http/Controllers/DirMarkController.php
<?php

namespace App\Http\Controllers;

use App\DirMark;
use Illuminate\Http\Request;

/**
 * Class DirMarkController
 * @package App\Http\Controllers
 */
class DirMarkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dirMarks = DirMark::paginate();
        return $this->selfView('dir-mark.index', compact('dirMarks'), (request()->input('page', 1) - 1) * $dirMarks->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dirMark = new DirMark();
        return view('dir-mark.create', compact('dirMark'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(DirMark::$rules);

        $dirMark = DirMark::create($request->all());

        return redirect()->route('dirmark.index')
            ->with('success', 'Guide Mark created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dirMark = DirMark::find($id);

        return $this->selfView('dir-mark.show', compact('dirMark'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dirMark = DirMark::find($id);

        return $this->selfView('dir-mark.edit', compact('dirMark'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  DirMark $dirMark
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate(DirMark::$rules);
        DirMark::find($id)->update($request->all());
        return redirect()->route('dirmark.index')
            ->with('success', 'Guide Mark updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        DirMark::find($id)->delete();
        return redirect()->route('dirmark.index')
            ->with('success', 'Guide Mark deleted successfully');
    }
}

resources/views/dir-mark/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.Create') }} {{ __('all.GuideMark') }}
@endsection

@section('template_button')
    <a href="{{ route('dirmark.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-body">
                        <form method="POST" action="{{ route('dirmark.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('dir-mark.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dir-mark/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.Update') }} {{ __('all.GuideMark') }}
@endsection

@section('template_button')
    <a href="{{ route('dirmark.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> {{ __('all.button.Back') }}</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-body">
                        <form method="POST" action="{{ route('dirmark.update', $dirMark->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('dir-mark.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dir-mark/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            {{ Form::label( __('all.table.Name') ) }}
            {{ Form::text('name', $dirMark->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => __('all.table.Name') ]) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label(__('all.table.Color')) }}
            {{ Form::color('color', $dirMark->color, ['class' => 'form-control' . ($errors->has('color') ? ' is-invalid' : ''), 'placeholder' => __('all.table.Color')]) }}
            {!! $errors->first('color', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('all.button.Submit') }}</button>
    </div>
</div>

resources/views/dir-mark/index.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.GuidesMarks') }}
@endsection

@section('template_button')
    <a href="{{ route('dirmark.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
        <i class="fas fa-plus-circle"></i> {{ __('all.button.CreateNew') }}
    </a>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        @include('layouts.alerts.success')

                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>{{ __('all.table.No') }}</th>

										<th>{{ __('all.table.Name') }}</th>
										<th>{{ __('all.table.Color') }}</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($dirMarks as $dirMark)
                                        <tr>
                                            <td>{{ ++$i }}</td>

											<td>{{ $dirMark->name }}</td>
											<td>{{ $dirMark->color }} <span class="badge" style="background-color: {{ $dirMark->color }}; color: #ffffff">Color View</span></td>

                                            <td>
                                                <form action="{{ route('dirmark.destroy',$dirMark->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('dirmark.show',$dirMark->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('all.button.Show') }}</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('dirmark.edit',$dirMark->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('all.button.Edit') }}</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> {{ __('all.button.Delete') }}</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $dirMarks->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/dir-mark/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('all.button.Show') }} {{ __('all.GuideMark') }}
@endsection

@section('template_button')
    <a href="{{ route('dirmark.index') }}" class="btn btn-primary btn-sm float-right"  data-placement="left"> Back</a>
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        <div class="form-group">
                            <strong>{{ __('all.table.Name') }}:</strong>
                            {{ $dirMark->name }}
                        </div>
                        <div class="form-group">
                            <strong>{{ __('all.table.Color') }}:</strong>
                            {{ $dirMark->color }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection